### ISSUE TITLE
Windows 7 error: libssl is missing

### ISSUE THREAD

**Issue by sergeevabc** [khrynczenko/RadioStream#81]
![image](https://user-images.githubusercontent.com/373718/200467274-c6b0f440-f57b-45d0-a8f3-a50233817eb4.png)

**Comment by khrynczenko** [comment]
Hi @sergeevabc,
I assume that the problem is when you try to run the application not build it. It seems I do not bundle **libssl** binary with the application and assume that it is installed on your system and in your **PATH**. If you want to quickly fix the problem on your end please install openssl 1.1. There are a couple of ways of doing it. One is to use [choco](https://community.chocolatey.org/packages/openssl). Other is to download files from [sourceforge](https://sourceforge.net/projects/openssl-for-windows/) and add the directory to your **PATH**.

In the meantime, I will try to find what can I do about it to make it easier. If you need any additional help or have any questions please let me know.

**Comment by khrynczenko** [comment]
I release a new version with these dlls included. Hopefully, it helps. You can download them from the following link.
https://github.com/khrynczenko/RadioStream/releases/tag/v0.2.2

**Comment by sergeevabc** [comment]
@khrynczenko, it launches now as expected. However it looks a bit messy after resize.

![20221109_radiostream_01](https://user-images.githubusercontent.com/373718/200697794-b5eebdf0-b866-4b0d-89af-1650995974dd.png)
